### ISSUE TITLE
Support path with named entry elements containing a slash

### ISSUE THREAD

**Issue by HeavyWombat** [HeavyWombat/ytbx#1]
Support grabbing things like:
```yaml
---
override:
- name: k8s.io/api
  branch: release-1.10
```
with path `/override/name=k8s.io\/api`
